kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kafka-ui
  namespace: hackfest2023
  labels:
    app: kafka-ui
    app.kubernetes.io/component: kafka-ui
    app.kubernetes.io/instance: kafka-ui
    app.kubernetes.io/name: kafka-ui
    app.kubernetes.io/part-of: qiot-retail-edgepos-manager-git-app
    app.openshift.io/runtime-version: latest
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: kafka-ui-hackfest2023.apps.hackfest2023.viada.de
  to:
    kind: Service
    name: kafka-ui
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
